### PR TITLE
Make resolve test failures easier to debug.

### LINKED ISSUE #263: resolve/cmd: test failures show no output, test passes show no test names
Something very strange is going on with the resolve/cmd tests. If you run "go test -v", it does not list the test names that pass:

%  go test -v github.com/grafeas/kritis/cmd/kritis/kubectl/plugins/resolve/cmd/...                                                                                                                                                 
PASS
ok      github.com/grafeas/kritis/cmd/kritis/kubectl/plugins/resolve/cmd        0.734s

When a test fails, it likewise does not mention what test failed:

%  go test -v github.com/grafeas/kritis/cmd/kritis/kubectl/plugins/resolve/cmd/...                                                                                                                                                 exit status 1
FAIL    github.com/grafeas/kritis/cmd/kritis/kubectl/plugins/resolve/cmd        0.690s

When you try to list the names of the tests, it returns nothing:

%  go test -list ".*" -v github.com/grafeas/kritis/cmd/kritis/kubectl/plugins/resolve/cmd/...                                                                                                                                   PASS
ok      github.com/grafeas/kritis/cmd/kritis/kubectl/plugins/resolve/cmd        0.657s

I suspect something relating to flag parsing and cmd.Init().

### PR DESCRIPTION
**Pull request by tstromberg**
- Remove Exit & Fatalf calls so that tests don't quietly exit
- Propagate errors upward
- Improve error messages
- Document an important note that these tests are not hermetic (*eek!*)
- Fix some spelling mistakes

Fixes #263

### CODE REVIEW

File: cmd/kritis/kubectl/plugins/resolve/main.go [hunk 1]
```diff
@@ -17,15 +17,13 @@ limitations under the License.
...
-	"fmt"
 	"os"
 
 	"github.com/grafeas/kritis/cmd/kritis/kubectl/plugins/resolve/cmd"
 )
 
 func main() {
 	if err := cmd.RootCmd.Execute(); err != nil {
-		fmt.Println(err)
 		os.Exit(1)
```
Comment (priyawadhwa) [inline cmd/kritis/kubectl/plugins/resolve/main.go]: Why was this removed?

Comment (priyawadhwa) [reply cmd/kritis/kubectl/plugins/resolve/main.go]: cool, thanks for explaining!
